=== CAST-projects/ProtoZBuffer/ProtoZBuffer/protozbuff.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="protoZ"
    targetNamespace="http://tempuri.org/protoZ.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/protoZ.xsd"
    xmlns:mstns="http://tempuri.org/protoZ.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="protozbuff" type="protozbuffType"/>
  
  <xs:complexType name="protozbuffType">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="message" type="messageType" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="enum" type="enumType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute name="description" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:simpleType name="typeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="double"/>
      <xs:enumeration value="float"/>
      <xs:enumeration value="int32"/>
      <xs:enumeration value="int64"/>
      <xs:enumeration value="uint32"/>
      <xs:enumeration value="uint64"/>
      <xs:enumeration value="sint32"/>
      <xs:enumeration value="sint64"/>
      <xs:enumeration value="fixed32"/>
      <xs:enumeration value="fixed64"/>
      <xs:enumeration value="sfixed32"/>
      <xs:enumeration value="sfixed64"/>
      <xs:enumeration value="bool"/>
      <xs:enumeration value="string"/>
      <xs:enumeration value="bytes"/>
      <xs:enumeration value="referenceMessage"/>
      <xs:enumeration value="nestedMessage"/>
      <xs:enumeration value="enum"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="modifierType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="required"/>
      <xs:enumeration value="optional"/>
      <xs:enumeration value="repeated"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="fieldType">
    <xs:attribute name="id" type="xs:int" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="type" type="typeType" use="required"/>
    <xs:attribute name="messageType" type="xs:string" use="optional"/>
    <xs:attribute name="enumType" type="xs:string" use="optional"/>
    <xs:attribute name="modifier" type="modifierType" use="required"/>
    <xs:attribute name="default" type="xs:string" use="optional"/>
    <xs:attribute name="description" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="indexType">
    <xs:attribute name="id" type="xs:int" use="required"/> <!-- same as field id -->
    <xs:attribute name="name" type="xs:string" use="optional"/>
    <xs:attribute name="forField" type="xs:int" use="required"/> <!-- id of the field to sort. Field must be repeated. -->
    <xs:attribute name="sortBy" type="xs:string" use="required"/> <!-- name of the field's attribute used for sorting -->
    <xs:attribute name="description" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="enumType">
    <xs:sequence>
      <xs:element name="enumItem" type="enumElementType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="description" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name ="enumElementType">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use ="required"/>
    <xs:attribute name="description" type="xs:string" use="optional"/>
  </xs:complexType>
  
  <xs:complexType name="messageType">
    <xs:sequence>
      <xs:element name="field" type="fieldType" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="index" type="indexType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"  use="required"/>
    <xs:attribute name="description" type="xs:string" use="optional"/>
  </xs:complexType>

</xs:schema>

=== CAST-projects/ProtoZBuffer/TestGeneratedCodeCpp/FileStructure.xml
<?xml version="1.0" encoding="utf-8"?>
<protozbuff xmlns="http://tempuri.org/protoZ.xsd"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="..\ProtoZBuffer.Core\protozbuff.xsd">
  <!-- Dummy comment to force regeneration (add a dot): . -->
  <message name="Document" description="Root node of the document. Used to unit test ProtoZBuffer">
    <field id="1" modifier="repeated" name="data" type="nestedMessage" description="The data itself" messageType="Data" />
  </message>

  <message name="Data" description="Data stored in the document. This fake data will contain many data types for testing purposes">
    <field id="1" modifier="required" name="identification" type="nestedMessage" messageType="Identity" />
    <field id="2" modifier="optional" name="secretIdentity" type="nestedMessage" messageType="Identity" />
    <field id="3" modifier="repeated" name="reviewers" type="referenceMessage" messageType="Identity" />
    <field id="4" modifier="optional" name="approver" type="referenceMessage" messageType="Identity" />
  </message>

  <message name="Identity">
    <field id="1" modifier="required" name="firstName" type="string" />
    <field id="2" modifier="optional" name="birthYear" type="int32" />
  </message>
  
</protozbuff>
